name: CommitChecks

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: macos-15

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "26"
      - uses: actions/checkout@v2
      - name: xcbeautify
        run: brew install xcbeautify
      - name: Run Test
        run: swift test
