name: CommitChecks

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: macos-14

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "16.1"
      - uses: actions/checkout@v2
      - name: Run Test
        run: set -o pipefail && xcodebuild -scheme Normalization test -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1' | xcbeautify
